kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-log
  namespace: devops
  annotations:
    volume.beta.kubernetes.io/storage-class: "iiidevops-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  
