apiVersion: v1
kind: Service
metadata:
  name: sonarqube-server-service
  namespace: devops
  labels: 
    app: sonarqube-server
spec:
  type: ClusterIP
  selector:
    app: sonarqube-server
  ports:
    - name: apiport
      protocol: TCP
      port: 9000
